apiVersion: v1
kind: Service
metadata:
  name: mighty-fine-fe
spec:
  type: NodePort
  selector:
    app: mighty-fine-fe
  ports:
    - port: 3000
      name: http
      targetPort: 3000
      nodePort: 30001